### ISSUE TITLE
can't find the right .NET Framework to get this to work

### ISSUE THREAD

**Issue by killerluigi91** [malware-dev/MDK-SE#167]
I have tried 10 .NET Framework Packs and none of them work. so what is the best NET pack to use on this?

**Comment by malware-dev** [comment]
As it says in the instructions, you need the .NET Framework 4.6.1 targeting pack.

**Comment by malware-dev** [comment]
Given that I am not getting any further comment I will assume this is resolved.

**Comment by killerluigi91** [comment]
Nope just stopped messing with i updated VS and it still wont work.

**Comment by malware-dev** [comment]
Sorry to hear that.

"won't work" is not very informative though. What exactly is it that doesn't work?
